config/routes.rb
Fenway::Application.routes.draw do
  resources :users

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  resources :state, only: [:show, :update], defaults: { format: 'json' } do
    put 'single'
    put 'double'
    put 'triple'
    put 'ball'
    put 'steal'
    put 'strike'
    put 'next_inning'
    put 'start_game'
    put 'homerun'
    put 'score'
    put 'move'
    put 'out'
  end

  resources :games do
  	get 'score'
    post 'score'
  end


  resources :players do
    put 'new_user', :on => :collection
  end

  resources :teams do
    get 'autocomplete_user_name', :on => :collection
    get 'autocomplete_team_name', :on => :collection
    resources :players do
      put 'update_jersey_number'
      put 'destroy'
    end
  end

  root to: 'home#index'
end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :away_team, class_name: "Team"
  belongs_to :home_team, class_name: "Team"
  has_many :stats

  EVENTS = ["strike", "ball", "walk", "out", "away_point", "home_point"]

  def players
    away_team.players + home_team.players
  end

  def in_progress?
    return true if self.start_datetime && self.start_datetime <= DateTime.now
    false
  end

  def away_lineup
    vl = read_attribute(:away_lineup)
    return [] unless vl
    vl.split(',')
  end
  def away_lineup= lineup
    write_attribute(:away_lineup, lineup.join(','))
  end

  def home_lineup
    hl = read_attribute(:home_lineup)
    return [] unless hl
    hl.split(',')
  end
  def home_lineup= lineup
    write_attribute(:home_lineup, lineup.join(','))
  end

  def start_datetime
    return nil unless start_date
    start_time ||= Time.now.beginning_of_day
    DateTime.new(start_date.year, start_date.month, start_date.day, start_time.hour, start_time.min, start_time.sec)
  end

  def handle event
    raise "Invalid event" unless EVENTS.include? event
    GameState.new(self.id).send(event)
  end
end

app/models/game_state/game.rb
module GameState
  class Game < State
    attr_reader :date
    attr_reader :lineups, :inning
    attr_reader :away_score, :home_score
    attr_accessor :socket_id

    def initialize(id)
      super(id)
      @lineups = Lineups.new(id)
      @inning = Inning.new(id)
    end

    def single!
      set(:balls, 0)
      set(:strikes, 0)
      player_id = lineups.active(@inning).to_base 1
      r.set(key(:last_to_bat), player_id)
      pusher 'single'
      sf = StatFactory.new id, @inning
      sf.single(player_id)
    end

    def double!
      set(:balls, 0)
      set(:strikes, 0)
      player_id = lineups.active(@inning).to_base 2
      r.set(key(:last_to_bat), player_id)
      pusher 'double'
      sf = StatFactory.new id, @inning
      sf.double(player_id)
    end

    def triple!
      set(:balls, 0)
      set(:strikes, 0)
      player_id = lineups.active(@inning).to_base 3
      r.set(key(:last_to_bat), player_id)
      pusher 'triple'
      sf = StatFactory.new id, @inning
      sf.triple(player_id)
    end

    def homerun!
      set(:balls, 0)
      set(:strikes, 0)
      player_id = lineups.active(@inning).to_base 4
      r.set(key(:last_to_bat), player_id)   
      run! @inning.top? ? 0 : 1
      pusher 'homerun'
      sf = StatFactory.new id, @inning
      sf.homerun(player_id)
    end

    def run! topOrBottom
      Rails.logger.info "RUNNGINGGG::::::#{topOrBottom}"
      if topOrBottom == 0
        Rails.logger.info "MORE AWAY SCORE!!!!"
        increment_away_score
      else
        Rails.logger.info "MORE HOME SCORE!!!!"
        increment_home_score
      end
      pusher 'run', top: topOrBottom
      sf = StatFactory.new id, @inning
      sf.rbi r.get(key(:last_to_bat))
      sf.homerun 0
    end

    def on_base base_id
      temp = bases[base_id - 1]
      pusher 'on_base', base_id: base_id
      if temp == nil
        return 0
      else
        return temp
      end
    end

    def player_on_base base_id #THIS IS WRONG, but ryan is lazy at 3am.
      User.find(on_base(base_id))
    end

    def bases
      get_int_array :bases
    end

    def at_bat
      lineups.active(@inning).next
    end

    def out! player_id
      if(player_id == at_bat)
        s = lineups.active(@inning).to_out
        r.set(key(:last_to_bat), player_id)
      else
        s = r.lrem key(:bases), 0, player_id
      end
      out
      pusher 'out', player_id: player_id
      sf = StatFactory.new id,@inning
      sf.strike_out s
    end

    def strikes
      get(:strikes).to_i
    end

    def strike!
      strikes = r.incr(key :strikes)
      self.out if strikes == 3
      pusher 'strike'
    end

    def strikes= num
      set(:strikes, num)
    end

    def balls
      get(:balls).to_i
    end

    def ball!
      balls = r.incr(key :balls)
      self.walk! if balls == 4
      pusher 'ball'
    end

    def balls= num
      set(:balls, num)
    end

    def walk!
      pusher 'walk' unless balls == 4 #this was an autowalk, don't push
      r.pipelined do
        set(:balls, 0)
        set(:strikes, 0)
      end
      player_id = lineups.active(@inning).to_base 1
      r.set(key(:last_to_bat), player_id)
      ##TODO(rfahsel3) Log a stat
    end

    def outs
      get(:outs).to_i
    end

    def outs= num
      set(:outs, num)
    end

    def out
      r.pipelined do
        outs = r.incr(key :outs)
        set(:balls, 0)
        set(:strikes, 0)
      end
      next_inning! if outs >= 3
    end

    def next_inning!
      set(:outs, 0)
      r.del(key :bases)
      @inning.next
      pusher 'next_inning'
    end

    def away_score!
      r.incr(key :away)
      pusher 'away_score'
    end

    def home_score!
      r.incr(key :home)
      pusher 'home_score'
    end

    def move! player_id, new_base, is_steal
      temp = bases
      if new_base == 2
        temp[1] = temp[0]
        temp[0] = 0
      elsif new_base == 3
        temp[2] = temp[1]
        temp[1] = 0
      elsif new_base == 4
        temp = [0,0,0]
        #TODO, score a run
        sf = StatFactory.new id,@inning
        sf.rbi player_id
      end
      set_array key(:bases), temp
      pusher 'move', {player_id: player_id, new_base: new_base, is_steal: is_steal == 1}
      if is_steal == 1
        sf = StatFactory.new id,@inning
        sf.steal player_id
      end
    end

    def increment_away_score
      r.incr(key(:away_score))
    end

    def away_score
      r.get(key(:away_score)).to_i
    end

    def increment_home_score
      r.incr(key(:home_score))
    end

    def home_score
       r.get(key(:home_score)).to_i
    end

    def expire
      @date = Time.now
      epoch = @date.to_i
      r.pipelined do
        lineups.set_expiration(epoch)
        inning.set_expiration(epoch)
        set_expiration(epoch)
      end
    end

    private
    def pusher(event, data = {})
      @socket_id ||= ""
      return if Rails.env == "test"
      Pusher.trigger_async('game_state_'+@id.to_s, event, data, {socket_id: @socket_id})
    end

    def set_expiration epoch
        r.expireat(key(:bases), epoch)
        r.expireat(key(:away), epoch)
        r.expireat(key(:home_score), epoch)
        r.expireat(key(:away_score), epoch)
        r.expireat(key(:home), epoch)
        r.expireat(key(:balls), epoch)
        r.expireat(key(:strikes), epoch)
        r.expireat(key(:outs), epoch)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show,:edit,:update, :destroy]

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def show
    @game = Game.find(params[:id]).decorate
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      flash[:success] = "Saved game"
      redirect_to games_path
    else
      flash[:error] = "Could not save game"
      render action: 'new'
    end
  end

  def update
    @game.update_attributes(game_params)

    respond_to do |format|
      format.html {redirect_to @game}
      format.json {respond_with_bip(@game)}
    end
  end

  def score
    @game = Game.find(params[:game_id]).decorate
    return unless params[:score].present?

    respond_to do |format|
      @game.handle(params[:score])
      if @game.save
        format.html { redirect_to game_score_path(@game), notice: params[:score] }
        format.json { head :ok }
      else
        format.html { redirect_to game_score_path(@game), error: "Bad things happened" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(
      :name, :start_time, :start_date, :location, :away_team_id, :home_team_id
    )
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def diamond_icon base, name
    active = base.present? && base != 0 ? "active" : ""
    '<span class="diamond '+name+' '+active+'" ></span>'.html_safe
  end
end

app/views/games/_form.slim
= simple_form_for @game do |f|
  = f.input :name
  = f.input :start_date, as: :string
  = f.input :start_time
  = f.input :location
  = f.association :away_team
  = f.association :home_team
  = f.submit
javascript:
  $('#game_start_date').datepicker({format: 'yyyy-mm-dd'});

app/views/games/_game.html.slim
tr
	td = link_to game.name, game_path(:id => game.id)
	td 
		= best_in_place game, :start_date, :type => :input, activator: "#edit_game_#{game.id}_date"
		= " "
		a href="#"
			i.icon-calendar id="edit_game_#{game.id}_date"
	td
		= best_in_place game, :start_time, :type => :input, :display_with => Proc.new { |f| f.strftime("%H:%M") }, activator: "#edit_game_time_#{game.id}"
		= " "
		a href="#"
			i.icon-edit id="edit_game_time_#{game.id}"

javascript:
	$(".picker_game_time").datepicker({format: 'yyyy-mm-dd'});

app/views/games/_mobile_score.html.slim
.score_overview
  .banner
    .conatiner
      .row
        h2 id="game_date" 
          |Start date: 
          = @game.start_date
  .overview
    - @game_state = GameState::Game.find(@game.id)
    .container  
      .row
        table.score
          tr.away_team
            td.team_name = @game.away_team.name
            td.score = @game_state.away_score
          tr.home_team
            td.team_name = @game.home_team.name
            td.score = @game_state.home_score
        .info
          .bases
            == diamond_icon @game_state.bases[1], 'first'
            == diamond_icon @game_state.bases[2], 'second'
            == diamond_icon @game_state.bases[3], 'third'

          p.balls.strikes.outs
            = @game_state.balls
            = "-"
            = @game_state.strikes
            = "   "
            = @game_state.outs
        .inning
          .current
            p
              - if @game_state.inning.top?
                = "Top "
              - else
                = "Bottom "
              = @game_state.inning.to_number
.detail
  table.scores_by_inning
    thead
      th
      - (1..9).each do |i|
        th = i
      th.runs R
      th H
      th E
    tbody
      tr.home_team
        - @home_team_stats = @game.home_team.stats.where(game_id: @game.id)
        td.name = @game.home_team.name
        - (1..9).each do |i|
          td data-number=i = Stat.homeruns_by_inning(@home_team_stats, i)
        td.runs = @game_state.home_score
        td.hits = Stat.hits(@home_team_stats)
        td.errors 0
      tr.away_team
        - @away_team_stats = @game.away_team.stats.where(game_id: @game.id)
        td.name = @game.away_team.name
        - (1..9).each do |i|
          td data-number=i = Stat.homeruns_by_inning(@away_team_stats, i)
        td.runs = @game_state.away_score
        td.hits = Stat.hits(@away_team_stats)
        td.errors 0

app/views/games/edit.slim
== render "form"

app/views/games/index.slim
.container
  .row
    .pull-left
      h1 Games
      h2 Play. Score. Repeat.
    = link_to "Schedule Game", new_game_path, class: "btn btn-primary btn-large pull-right btn-header"
    .clearfix
    p Baseball games shoud be about the love of the game, not hindered by out of date scoreboards and unavailable scorekeeping. Fenway is the future of baseball scoring systems and is a fun easy way for anyone to have scoring for their baseball league. Spend your money making your field awesome, not your scoreboard. Now go out and play, score, and repeat!

    h2.grey_title Game Feed

.grey_background.game_feed
  .container
    .row
      - if @games.size == 0
        p Sorry no active games right now.
      - else
        - @games.each do |g|
          h2 = link_to g.name, game_score_path(g)
          - @game = g
          
          == render :partial => 'mobile_score', :object => @game

app/views/games/new.slim
.container
  .row
    h1 New Game
    == render 'form'

app/views/games/score.slim
.container
  .row
    h1.game_name = link_to @game.name, game_path(@game)
    #connection-status
      h2 Connection:
      p Disconnected
      button.btn onClick="do_refresh()" Refresh
  	.scoreboard
      p.game-status = @game.status_tag
      .scoring
        .home-team
          h4.team-name = @game.home_team.try(:name)
        .home-team-score
          h1.score 0
        .away-team
          h4.team-name = @game.away_team.try(:name)
        .away-team-score
          h1.score 0

        table id="innings-grid"
          tbody
            - if @game.away_team
              tr id="away-inning-row"
                - (1..10).each do |i|
                  td.innings-top data-number=i 0
            - else
              tr
                td hmm

            - if @game.home_team
              tr id="home-inning-row"
                - (1..10).each do |i|
                  td.innings-btm data-number=i 0

      - if @game.home_team
        .info id="home-team-id"
        .lineup id="home-lineup"
          ul.sortable id="home-list"
            h3
              =@game.home_team.name[0..2]
              |  Lineup

      - if @game.away_team
        .lineup id="away-lineup"
          ul.sortable id="away-list"
            h3
              =@game.away_team.name[0..2]
              |  Lineup
    	button.btn.btn-large id="startBtn" onClick="do_start_game()" Start Game
    	button.btn.btn-large id="strikeBtn" onClick="do_strike()" Strike
    	button.btn.btn-large id="ballBtn" onClick="do_ball()" Ball
    	a.circle id="home" data-placement="right" data-toggle="popover" data-title="Player0" data-html="true" data-content="<ul class='nav nav-tabs nav-stacked'><li><a onClick='do_single()'>Single</a></li><li><a onClick='do_double()'>Double</a></li><li><a onClick='do_triple()'>Triple</a></li><li><a onClick='do_homerun()'>Home Run</a></li><li><a onClick='do_out_onbase(0)'>Out</a></li><li><a onClick='do_walk()'>Walk</a></li></ul>" hidden="true"
    		h4 0
    	a.circle id="first" data-placement="right" data-toggle="popover" data-title="Player1"data-html="true" data-content="<ul class='nav nav-tabs nav-stacked'><li><a onClick='do_move(1,1)'>Steal</a></li><li><a onClick='do_move(1,0)'>Move</a></li><li><a onClick='do_out_onbase(1)'>Out</a></li></ul>" hidden="true"
    		h4 1
    	a.circle id="second" data-placement="bottom" data-toggle="popover" data-title="Player2"data-html="true" data-content="<ul class='nav nav-tabs nav-stacked'><li><a onClick='do_move(2,1)'>Steal</a></li><li><a onClick='do_move(2,0)'>Move</a></li><li><a onClick='do_out_onbase(2)'>Out</a></ul>" hidden="true"
    		h4 2
    	a.circle id="third" data-placement="left" data-toggle="popover" data-title="Player3"data-html="true" data-content="<ul class='nav nav-tabs nav-stacked'><li><a onClick='do_move(3,1)'>Steal</a></li><li><a onClick='do_move(3,0)'>Score</a></li><li><a onClick='do_out_onbase(3)'>Out</a></li></ul>" hidden="true"
    		h4 3

    	.score-light id="ball1" hidden="true"
    	.score-light id="ball2" hidden="true"
    	.score-light id="ball3"	hidden="true"

    	.score-light id="strike1" hidden="true"
    	.score-light id="strike2" hidden="true"

    	.score-light id="out1" hidden="true"
    	.score-light id="out2" hidden="true"

#mobilesocreboard
  == render :partial => 'mobile_score', :object => @game

javascript:
  var PUSHER_KEY = "#{Pusher.key}"
	$('#home').popover();
	$('#first').popover();
	$('#second').popover();
	$('#third').popover();
	$('.sortable').sortable();
	$('.sortable').disableSelection();

app/views/games/show.html.slim
.container
  .row   
    h1 = @game.name
    h4
      = link_to 'Edit', edit_game_path(@game)
      = " | "
      = link_to 'Back', games_path

    .well
      h3 Location
      p = @game.location

      h3 Start Time
      p = @game.start_time

      h3 Start Date
      p = @game.start_date

      h3 Home Team
      - if @game.home_team
        p = link_to @game.home_team.name, team_path(@game.home_team)

      h3 Away Team
      - if @game.away_team
        p = link_to @game.away_team.name, team_path(@game.away_team)