config/routes.rb
Fenway::Application.routes.draw do
  resources :users

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  resources :state, only: [:show, :update], defaults: { format: 'json' } do
    put 'single'
    put 'double'
    put 'triple'
    put 'ball'
    put 'steal'
    put 'strike'
    put 'next_inning'
    put 'start_game'
    put 'homerun'
    put 'score'
    put 'move'
    put 'out'
  end

  resources :games do
  	get 'score'
    post 'score'
  end


  resources :players do
    put 'new_user', :on => :collection
  end

  resources :teams do
    get 'autocomplete_user_name', :on => :collection
    get 'autocomplete_team_name', :on => :collection
    resources :players do
      put 'update_jersey_number'
      put 'destroy'
    end
  end

  root to: 'home#index'
end

app/models/player.rb
class Player < ActiveRecord::Base
	belongs_to :team
	belongs_to :user

	def name
		user.name
	end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
  end

  def show
    @player = Player.find(params[:id])
    @team = Team.find(@player.team_id)
  end

  def index
    @users = User.where(id: Player.all.pluck(:id)).order(:name)
  end

	def edit
		respond_to do |format|
      format.html { redirect_to team_player_path}
      format.js
    end
	end

	def create
    @user = User.where(:name => params[:player][:user][:name]).first
    @team = Team.find(params[:team_id])

    if @user != nil
      @player = Player.new
      @player.team_id = params[:team_id]
      @player.user_id = @user.id
      @player.save
      flash[:success] = "Player added to team."
    else
      flash[:error] = "User does not exist."
    end
    respond_to do |format|
      format.html { redirect_to Team.find(params[:team_id]) }
      format.js
    end
    
	end

  def add
    @player = Player.new
    @player.team_id = params[:team_id]
    @player.save

    respond_to do |format|
      format.json { respond_with_bip(@player) }
    end
  end

  def destroy
    @player = Player.find(params[:player_id])
    @player.destroy
    redirect_to Team.find(params[:team_id])
  end

  def update_jersey_number
    @player = Player.find(params[:player_id])
    @player.player_number = params[:player][:player_number].to_i
    @player.save

    respond_to do |format|
      format.json { respond_with_bip(@player) }
    end
  end

  def new_user
    @user = User.create(user_params)
    @player = Player.new
    @player.user_id = @user.id
    @player.save
    redirect_to players_path
  end

	private
	def player_params
		params.require(:player).permit(
			:team_id, :user_id, :player_number
		)
	end

  def user_params
    params[:player].require(:user).permit(
      :name, :email
    )
  end
end

app/views/players/_edit.html.slim
= simple_form_for player, remote: true do |f|
	td = player.user.name
	td = f.input :player_number
	td = f.submit

app/views/players/_new_player.html.slim
tr id="new_player_row"
	
	td 
		= simple_form_for [team, player], remote: true do |f|
			= f.simple_fields_for :user do |u|
				= u.input :name, :url => autocomplete_user_name_teams_path, :as => :autocomplete
	td -
	td	
		i.icon-remove-sign

app/views/players/_player.html.slim
tr id="player_#{player.id}_info"

	td = link_to player.user.name, team_player_path(:team_id => team.id, :id => player.id)
	td 
		= best_in_place player, :player_number, :type => :input, :path => team_player_update_jersey_number_path(:team_id => team.id, :player_id => player.id), activator: "#edit_player_#{player.id}_number"
		= " "
		i.icon-pencil id="edit_player_#{player.id}_number"
	td 
		= link_to team_player_destroy_path(:team_id => team.id, :player_id => player.id), :method => :put
			i.icon-remove-sign

app/views/players/create.js.erb
<% if @player != nil %>
  $("#new_player_row").remove();
  $("<%= escape_javascript(render :partial => 'players/player', :locals => {:team => @team, :player => @player}) %>").appendTo("#players").fadeIn();
<% else %>
  alert("test");
<% end %>

app/views/players/edit.html.slim
== render :partial => "edit", locals: {player: @player}

app/views/players/edit.js.erb
alert("here ok");

app/views/players/index.html.slim
.container
  .row
    .pull-left
      h1 Players
      h2 Race to the Top
    = link_to "Create New Player", "#new_player_modal", class: "btn btn-primary btn-large pull-right btn-header", :data => {:toggle => "modal"}
    .clearfix
    p Don't be left out of the scoring revolution! Join Fenway today, and experience what is like to focus on the playing the game instead of worrying about scoring. Play baseball games with friends, and compare statistics for bragging rights. Join in on the race to the top!
    .well
      - @users.each do |p|
        h3 = link_to p.name, p

  .modal.hide.fade id="new_player_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"

    .modal-header
      button.close data-dismiss="modal" aria-hidden="true" x
      h3 New Player

    .modal-body
      = simple_form_for Player.new, :url => new_user_players_path, :method => :put do |f|
        = f.simple_fields_for :user do |u|
          = u.input :name
          = u.input :email
        = f.submit

app/views/players/new.js.erb
$("<%= escape_javascript(render :partial => 'players/new_player', :locals => {:team => @team, :player => Player.new}).html_safe %>").appendTo("#players").fadeIn();

app/views/players/show.html.slim
.player_summary
  .container
    .row
      .pull-left
        img.player_img src="http://placehold.it/200x200"
      .pull-left
        h1.player_name = link_to @player.user.name, @player.user
        = link_to "Sign in to personalize", "#", class: "btn btn-mini"
        .clearfix
        .player_generic_info
          ul.player_generic_info.inline.large
            li = "##{@player.player_number} 3B"
            li.divider
            li = "Bats: R, Throws: R"
            li.divider
            li = link_to @player.team.name, @player.team
          .clearfix
          table.player_from_info
            tr
              td.desc Birth Date:
              td Unknown
            tr
              td.desc Birthplace:
              td Unknown
            tr 
              td.desc Affiliation:
              td Unkown
      .career_stats.pull-right
        h2 Career Stats
        - @games = Game.where("away_team_id=? or home_team_id=?", @player.team.id, @player.team.id)
        - @stats = Stat.where(user_id: @player.user.id, game_id: @games.pluck(:id))
        table.table.table-striped
          thead
            th AVG
            th HR
            th RBI
            th OBP
          tbody
            tr
              td id="average" = Stat.avg(@stats)
              td id="homeruns" = Stat.homeruns(@stats)
              td id="rbi" = Stat.rbi(@stats)
              td id="obp" = Stat.obp(@stats)
        h2 Season Stats
        - @games = @games.where("DATE(start_date) >= ?", Date.new(Time.now.year,1,1))
        - @stats = Stat.where(user_id: @player.user.id, game_id: @games.pluck(:id))
        table.table.table-striped
          thead
            th AVG
            th HR
            th RBI
            th OBP
          tbody
            tr
              td id="" = Stat.avg(@stats)
              td id="" = Stat.homeruns(@stats)
              td id="" = Stat.rbi(@stats)
              td id="" = Stat.obp(@stats)
      .clearfix
.container
  .row
    h2 Bio
    p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc id mi libero. Praesent egestas erat vitae lorem feugiat, non convallis mi consequat. Phasellus ullamcorper sodales tellus at condimentum. Suspendisse vitae libero tempor, elementum dui sed, mattis justo. Vestibulum interdum facilisis sapien, non rutrum leo pretium sit amet. Curabitur adipiscing eros et purus imperdiet dictum. Nulla venenatis consectetur metus eu tempor. Curabitur ornare et nisl vitae congue. Cras commodo faucibus facilisis. Praesent condimentum eget mauris vel tristique.
    h2.grey_title More Info
.grey_background
  .contianer
    .row