config/routes.rb
Fenway::Application.routes.draw do
  resources :users

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  as :user do
    delete "/logout" => "devise/sessions#destroy"
  end

  resources :state, only: [:show, :update], defaults: { format: 'json' } do
    put 'single'
    put 'double'
    put 'triple'
    put 'ball'
    put 'steal'
    put 'strike'
    put 'next_inning'
    put 'start_game'
    put 'homerun'
    put 'score'
    put 'move'
    put 'out'
  end

  resources :games do
  	get 'score'
    post 'score'
  end


  resources :players do
    put 'new_user', :on => :collection
  end

  resources :teams do
    get 'autocomplete_user_name', :on => :collection
    get 'autocomplete_team_name', :on => :collection
    resources :players do
      put 'update_jersey_number'
      put 'destroy'
    end
  end

  root to: 'home#index'
end

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
        div class="alert #{name}"
            div id="flash_#{name}"
              = msg

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title Fenway
    = csrf_meta_tags

    = google_webfonts_init({google: ['Oxygen']})
    = stylesheet_link_tag "application", media: "all"
    = javascript_include_tag "application"
    script src="http://js.pusher.com/2.1/pusher.min.js" type="text/javascript"

  body data-controller="#{controller.controller_name}" data-action="#{controller.action_name}"
    .login-bar.navbar.navbar-fixed-top
      .navbar-inner
        .container
          - if not current_page?('/')
            = link_to "FENWAY", root_path, class: "brand"

          a.btn.btn-navbar data-toggle="collapse" data-target=".nav-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          .pull-right
            .nav-collapse.collapse
              .nav
                - if controller.controller_name == "games"
                  li = link_to "GAMES", games_path, class: "active"
                - else
                  li = link_to "GAMES", games_path

                - if controller.controller_name == "teams"
                  li = link_to "TEAMS", teams_path, class: "active"
                - else
                  li = link_to "TEAMS", teams_path

                - if controller.controller_name == "users" or controller.controller_name == "players"
                  li = link_to "PLAYERS", players_path, class: "active"
                -else
                  li = link_to "PLAYERS", players_path

    .container.clearfix
      .row
        ul.nav.pull-right id="sign_in"
          - if user_signed_in?
            .pull-right
              li = link_to current_user.name, user_path(current_user), :id => "user_name"
              li = link_to "Sign Out", "/logout", :method => :delete
          - else
            li.pull-right.clickable.nav-text = link_to "Sign In", user_omniauth_authorize_path(:google_oauth2)  


      / aside.static-nav id="static-nav"
      /   .accordion id="accordion1"
      /     .accordion-group
      /       .accordion-heading
      /         a.accordion-toggle data-toggle="collapse" data-parent="#accordion1" href="#games-collapse" Games
      /       .accordion-body.collapse id="games-collapse"
      /         .accordion-inner
      /           ul.nav
      /             li = link_to "All Games", games_path
      /             li= link_to "New Game", new_game_path
      /     .accordion-group
      /       .accordion-heading
      /         a.accordion-toggle data-toggle="collapse" data-parent="#accordion1" href="#teams-collapse" Teams
      /       .accordion-body.collapse id="teams-collapse"
      /         .accordion-inner
      /           ul.nav
      /             li = link_to "All Teams", teams_path, :id => "all-teams"
      /             li = link_to "New Team", new_team_path
      /     .accordion-group
      /       .accordion-heading
      /         a.accordion-toggle data-toggle="collapse" data-parent="#accordion1" href="#players-collapse" Players
      /       .accordion-body.collapse id="players-collapse"
      /         .accordion-inner
      /           ul.nav
      /             li= link_to "All Players", users_path
      /             li= link_to "New Player", new_user_path
      /     .accordion-group
      /       .accordion-heading
      /         a.accordion-toggle data-toggle="collapse" data-parent="#accordion1" href="#leaderboards-collapse" Leaderboards
      /       .accordion-body.collapse id="leaderboards-collapse"
      /         .accordion-inner
      /           ul.nav
      /             li= link_to "All Leaderboards", "/fix_me"

    .container
      .row
        #notice
          == render 'layouts/messages'

    == yield

    .main-article id="main-article"
    
   
      /.clearfix

      footer